#!/bin/sh

# run
#
# David Adams
# November 2020
#
# Shell script to run the simulation in run.C.

THTXZ=$1
SRESP=$2
SDECO=$3
RUN=$4
NEVT=$5
if [ -z "$SDECO" ]; then
  echo "Usage: $0 THTXZ SRESP SDECO [NOISE [RUN [NEVT]]]]"
  echo "       THTXZ = Track angle in XZ plane."
  echo "       SRESP = SCONV:NNBR:NBIN:SIGL:NOISE"
  echo "         SCONV = nosig for no signal"
  echo "               = noconv for no convolution"
  echo "               = conv1d for 1D convolution"
  echo "               = conv2d for 2D convolution"
  echo "          NNBR = # neighbor cells (on each side) in convolution"
  echo "          NBIN = # bins/wire"
  echo "          SIGL = Longitudinal smearing sigma [ticks]: 0, 1, 2 or 3"
  echo "         NOISE = noise level (e/tick, e.g. 90 for protoDUNE)"
  echo "         SDECO = DNAM:DOPT"
  echo "            DNAM = nodeco for no deconvolution"
  echo "                 = deco1d for 1D deconvolution"
  echo "              DOPT = dft for DFT deconvolution."
  echo "                   = dm for direct matrix deconvolution."
  echo "                   = fm for filtered matrix deconvolution."
  echo "                   = cm for chi-square matrix deconvolution."
  echo "                 = deco2d for 2D deconvolution"
  echo "           RUN = Run number and random seed."
  echo "          NEVT = # events (1 track per event)"
  exit 0
fi
if [ -z "$NOISE" ]; then
  NOISE=0.0
fi
if [ -z "$RUN" ]; then
  RUN=1
fi
if [ -z "$NEVT" ]; then
  NEVT=1
fi
rm -f wsave/* &&
rm -f *.png *.tpad
root.exe -b -q 'run.C('$THTXZ', "'$SRESP'", "'$SDECO'", '$RUN', '$NEVT')' | tee run.log &&
cp *.png wsave
makeIndex wsave
