#!/bin/sh

# run
#
# David Adams
# November 2020
#
# Shell script to run the simulation in run.C.

THTXZ=$1
SRESP=$2
IRECO=$3
NOISE=$4
RUN=$5
NEVT=$6
if [ -z "$IRECO" ]; then
  echo Usage: $0 THTXZ SRESP IRECO [NOISE [RUN [NEVT]]]]
  echo "       THTXZ = Track angle in XZ plane."
  echo "       SRESP = noconv for no convolution"
  echo "       SRESP = 1dconv or 1dconv:NNBR for 1D convolution"
  echo "       SRESP = NNBR:NBIN or NNBR:NBIN:SIGM for 2D convolution"
  echo "         NNBR = # neighbor cells (on each side) in convolution"
  echo "         NBIN = # bins/wire"
  echo "         SIGM = Longitudinal smearing sigma [ticks]: 0, 1, 2 or 3"
  echo "                nosig means no signal, e.g. noise only"
  echo "       IRECO = 0: No deconvolution."
  echo "               1: DFT deconvolution."
  echo "               2: Direct matrix deconvolution."
  echo "               3: Filtered matrix deconvolution."
  echo "               4: Chi-square matrix deconvolution."
  echo "       NOISE = noise level (ke/tick, e.g. 90 for protoDUNE)"
  echo "          RUN = Run number and random seed."
  echo "         NEVT = # events (1 track per event)"
  exit 0
fi
if [ -z "$NOISE" ]; then
  NOISE=0.0
fi
if [ -z "$RUN" ]; then
  RUN=1
fi
if [ -z "$NEVT" ]; then
  NEVT=1
fi
rm -f wsave/* &&
rm -f *.png *.tpad
root.exe -b -q 'run.C('$THTXZ', "'$SRESP'", '$IRECO', '$NOISE', '$RUN', '$NEVT')' | tee run.log &&
cp *.png wsave
makeIndex wsave
